# Site settings
title: The Oxford Comma
header-img: img/home-bg.png
email: your-email@yourdomain.com
copyright_name: TaraShankar
description: "A petridish of blogposts and ramblings to be read with caution."
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: ''
github_username:  stoicsleuth
facebook_username:  tshankr3
email_username:  tarashankar@watstory.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
